site_name: Neural Child Development System
site_description: Documentation for the Neural Child Development System
site_author: Neural Child Team
repo_url: https://github.com/yourusername/neural-child
repo_name: neural-child

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Installation: guides/getting-started.md
    - Quick Start: guides/quick-start.md
    - Basic Concepts: guides/basic-concepts.md
  - Core Components:
    - Overview: components/index.md
    - Child Model: components/child-model.md
    - Developmental Stages: components/developmental-stages.md
    - Psychological Systems: components/psychological-systems.md
    - Learning Systems: components/learning-systems.md
  - API Reference:
    - Overview: api/index.md
    - Child Model API: api/child-model.md
    - Developmental API: api/developmental.md
    - Psychological API: api/psychological.md
    - Learning API: api/learning.md
    - Utility API: api/utils.md
  - Architecture:
    - Overview: architecture/index.md
    - System Design: architecture/system-design.md
    - Data Flow: architecture/data-flow.md
    - State Management: architecture/state-management.md
    - Security: architecture/security.md
  - Examples:
    - Overview: examples/index.md
    - Basic Usage: examples/basic-usage.md
    - Advanced Usage: examples/advanced-usage.md
    - Integration: examples/integration.md
    - Testing: examples/testing.md
  - Development:
    - Contributing: guides/contributing.md
    - Code Style: guides/code-style.md
    - Testing Guide: guides/testing.md
    - Documentation: guides/documentation.md
  - Support:
    - Troubleshooting: support/troubleshooting.md
    - FAQ: support/faq.md
    - Release Notes: support/release-notes.md 